[build.environment]
  NODE_VERSION = "22"
[build]
  command = "pnpm run build"
  publish = ".output/public"
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/atuJunqHzc"
  status = 301
  force = true
