[build.environment]
  NODE_VERSION = "18"
[build]
  publish = "dist"
  command = "pnpm run build"
[[redirects]]
  from = "/guide/*"
  to = "https://docs.tresjs.org/guide/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/api/*"
  to = "https://docs.tresjs.org/api/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/examples/*"
  to = "https://docs.tresjs.org/examples/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/advanced/*"
  to = "https://docs.tresjs.org/advanced/:splat"
  status = 301
  force = true
